// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: robot_action/robot_action.proto

package robot_action

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for different types of actions
type ActionType int32

const (
	ActionType_KICK_ACTION    ActionType = 0
	ActionType_STOP_ACTION    ActionType = 1
	ActionType_MOVE_TO_ACTION ActionType = 2
	ActionType_INIT_ACTION    ActionType = 3
	ActionType_MOVE_ACTION    ActionType = 4
	ActionType_ROTATE_ACTION  ActionType = 5
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "KICK_ACTION",
		1: "STOP_ACTION",
		2: "MOVE_TO_ACTION",
		3: "INIT_ACTION",
		4: "MOVE_ACTION",
		5: "ROTATE_ACTION",
	}
	ActionType_value = map[string]int32{
		"KICK_ACTION":    0,
		"STOP_ACTION":    1,
		"MOVE_TO_ACTION": 2,
		"INIT_ACTION":    3,
		"MOVE_ACTION":    4,
		"ROTATE_ACTION":  5,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_robot_action_robot_action_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_robot_action_robot_action_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_robot_action_robot_action_proto_rawDescGZIP(), []int{0}
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommandId  ActionType `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3,enum=ActionType" json:"command_id,omitempty"`
	RobotId    int32      `protobuf:"varint,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	KickSpeed  int32      `protobuf:"varint,3,opt,name=kick_speed,json=kickSpeed,proto3" json:"kick_speed,omitempty"`
	Pos        *Vector3D  `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
	Dest       *Vector3D  `protobuf:"bytes,5,opt,name=dest,proto3" json:"dest,omitempty"`
	Direction  *Vector2D  `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	AngularVel int32      `protobuf:"varint,7,opt,name=angular_vel,json=angularVel,proto3" json:"angular_vel,omitempty"` // Negative value rotates robot clockwise
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_action_robot_action_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_robot_action_robot_action_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_robot_action_robot_action_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetCommandId() ActionType {
	if x != nil {
		return x.CommandId
	}
	return ActionType_KICK_ACTION
}

func (x *Command) GetRobotId() int32 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *Command) GetKickSpeed() int32 {
	if x != nil {
		return x.KickSpeed
	}
	return 0
}

func (x *Command) GetPos() *Vector3D {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Command) GetDest() *Vector3D {
	if x != nil {
		return x.Dest
	}
	return nil
}

func (x *Command) GetDirection() *Vector2D {
	if x != nil {
		return x.Direction
	}
	return nil
}

func (x *Command) GetAngularVel() int32 {
	if x != nil {
		return x.AngularVel
	}
	return 0
}

// Structure for 3D vector
type Vector3D struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32   `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32   `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W float32 `protobuf:"fixed32,3,opt,name=w,proto3" json:"w,omitempty"`
}

func (x *Vector3D) Reset() {
	*x = Vector3D{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_action_robot_action_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector3D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3D) ProtoMessage() {}

func (x *Vector3D) ProtoReflect() protoreflect.Message {
	mi := &file_robot_action_robot_action_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3D.ProtoReflect.Descriptor instead.
func (*Vector3D) Descriptor() ([]byte, []int) {
	return file_robot_action_robot_action_proto_rawDescGZIP(), []int{1}
}

func (x *Vector3D) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector3D) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Vector3D) GetW() float32 {
	if x != nil {
		return x.W
	}
	return 0
}

// Structure for 2D vector
type Vector2D struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Vector2D) Reset() {
	*x = Vector2D{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_action_robot_action_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2D) ProtoMessage() {}

func (x *Vector2D) ProtoReflect() protoreflect.Message {
	mi := &file_robot_action_robot_action_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2D.ProtoReflect.Descriptor instead.
func (*Vector2D) Descriptor() ([]byte, []int) {
	return file_robot_action_robot_action_proto_rawDescGZIP(), []int{2}
}

func (x *Vector2D) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2D) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_robot_action_robot_action_proto protoreflect.FileDescriptor

var file_robot_action_robot_action_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x72,
	0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xf5, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x2a, 0x0a,
	0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0b, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x62,
	0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x6f, 0x62,
	0x6f, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6b, 0x69, 0x63, 0x6b, 0x5f, 0x73, 0x70, 0x65,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6b, 0x69, 0x63, 0x6b, 0x53, 0x70,
	0x65, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x44, 0x52, 0x03, 0x70, 0x6f, 0x73,
	0x12, 0x1d, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x44, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x12,
	0x27, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x44, 0x52, 0x09, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6e, 0x67, 0x75,
	0x6c, 0x61, 0x72, 0x5f, 0x76, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61,
	0x6e, 0x67, 0x75, 0x6c, 0x61, 0x72, 0x56, 0x65, 0x6c, 0x22, 0x34, 0x0a, 0x08, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x33, 0x44, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x79, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x77, 0x22,
	0x26, 0x0a, 0x08, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x44, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x2a, 0x77, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x4b, 0x49, 0x43, 0x4b, 0x5f, 0x41, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x4f, 0x50, 0x5f, 0x41,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x4f, 0x56, 0x45, 0x5f,
	0x54, 0x4f, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x49,
	0x4e, 0x49, 0x54, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b,
	0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x11, 0x0a,
	0x0d, 0x52, 0x4f, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x05,
	0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c,
	0x69, 0x55, 0x2d, 0x53, 0x65, 0x65, 0x47, 0x6f, 0x61, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x72, 0x6f,
	0x62, 0x6f, 0x74, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_robot_action_robot_action_proto_rawDescOnce sync.Once
	file_robot_action_robot_action_proto_rawDescData = file_robot_action_robot_action_proto_rawDesc
)

func file_robot_action_robot_action_proto_rawDescGZIP() []byte {
	file_robot_action_robot_action_proto_rawDescOnce.Do(func() {
		file_robot_action_robot_action_proto_rawDescData = protoimpl.X.CompressGZIP(file_robot_action_robot_action_proto_rawDescData)
	})
	return file_robot_action_robot_action_proto_rawDescData
}

var file_robot_action_robot_action_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_robot_action_robot_action_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_robot_action_robot_action_proto_goTypes = []interface{}{
	(ActionType)(0),  // 0: ActionType
	(*Command)(nil),  // 1: Command
	(*Vector3D)(nil), // 2: Vector3D
	(*Vector2D)(nil), // 3: Vector2D
}
var file_robot_action_robot_action_proto_depIdxs = []int32{
	0, // 0: Command.command_id:type_name -> ActionType
	2, // 1: Command.pos:type_name -> Vector3D
	2, // 2: Command.dest:type_name -> Vector3D
	3, // 3: Command.direction:type_name -> Vector2D
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_robot_action_robot_action_proto_init() }
func file_robot_action_robot_action_proto_init() {
	if File_robot_action_robot_action_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_robot_action_robot_action_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_action_robot_action_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector3D); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_action_robot_action_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector2D); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_robot_action_robot_action_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_robot_action_robot_action_proto_goTypes,
		DependencyIndexes: file_robot_action_robot_action_proto_depIdxs,
		EnumInfos:         file_robot_action_robot_action_proto_enumTypes,
		MessageInfos:      file_robot_action_robot_action_proto_msgTypes,
	}.Build()
	File_robot_action_robot_action_proto = out.File
	file_robot_action_robot_action_proto_rawDesc = nil
	file_robot_action_robot_action_proto_goTypes = nil
	file_robot_action_robot_action_proto_depIdxs = nil
}
